# Generated by Django 5.2 on 2025-07-19 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_project', '0004_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='is_emp',
        ),
    ]
