# Generated by Django 5.2 on 2025-07-19 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_django_project', '0005_rename_is_staff_user_is_emp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_emp',
            new_name='is_staff',
        ),
    ]
